export const empty = {
  id: "CI2BpIUBlIy9zhf",
  duration: 53000,
  fps: 30,
  tracks: [],
  size: {
    width: 1080,
    height: 1920,
  },
  trackItemDetailsMap: {},
  trackItemIds: [],
  transitionsMap: {},
  trackItemsMap: {},
  transitionIds: [],
};

export const emptyDesignWidthMagneticTrack = {
  id: "dtpMWWHEkZLIpTa4",
  fps: 30,
  tracks: [
    {
      id: "M4mVODTbQZo4iTcI98Ysi",
      accepts: [],
      type: "customTrack",
      items: [],
      magnetic: true,
      static: true,
    },
  ],
  size: { width: 1080, height: 1920 },
  trackItemDetailsMap: {},
  trackItemIds: [],
  transitionsMap: {},
  trackItemsMap: {},
  transitionIds: [],
};

export const data = {
  id: "j1LfwJAoR9G3IhjE",
  fps: 30,
  tracks: [
    {
      id: "xZ5gKuKPPvq92Kc9X2SA2",
      accepts: [
        "text",
        "audio",
        "helper",
        "video",
        "image",
        "caption",
        "template",
      ],
      type: "text",
      items: ["rmf4bMElei2wRe8G"],
      magnetic: false,
      static: false,
    },
    {
      id: "roS-7tU5esh5R_mUXlsgl",
      accepts: [
        "text",
        "audio",
        "helper",
        "video",
        "image",
        "caption",
        "template",
      ],
      type: "caption",
      items: [
        "W1tb2sauODqNRhI5",
        "N326snvPf9O1XWB",
        "cpamVHqGkxVnQ2qp",
        "dvsBAKrDF6U0zTIV",
        "YpZM0yJx04Zb03zH",
        "CvXTedixwGMqnpS",
        "M2Sv36YckryY0NAS",
        "jxMeoaVX8BxOPEmS",
        "lM6VetPlAiCMU5T",
        "mdwLiXiu7SSFxSSB",
        "JC9MDYMvoHZkiu2w",
        "BWMEdVr9uGdg2pmN",
        "uSEooSKedBQi9eV",
        "a5JowII5uEpk6OQP",
      ],
      magnetic: false,
      static: false,
    },
    {
      id: "k5g9E_w1gSC-goCzJK9nB",
      accepts: [
        "text",
        "audio",
        "helper",
        "video",
        "image",
        "caption",
        "template",
      ],
      type: "video",
      items: ["RZUICjMxa7r3tM8K"],
      magnetic: false,
      static: false,
    },
    {
      id: "djmBmcR73Zpk1c1e",
      items: ["ic71GQgUoF393h2"],
      type: "audio",
      accepts: [
        "text",
        "audio",
        "helper",
        "video",
        "image",
        "caption",
        "template",
      ],
    },
  ],
  size: {
    width: 1080,
    height: 1920,
  },
  trackItemDetailsMap: {
    RZUICjMxa7r3tM8K: {
      type: "video",
      details: {
        width: 360,
        height: 640,
        opacity: 100,
        src: "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        volume: 100,
        borderRadius: 0,
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        top: "640px",
        left: "360px",
        transform: "scale(3)",
        blur: 0,
        brightness: 100,
        flipX: false,
        flipY: false,
        rotate: "0deg",
        visibility: "visible",
      },
      metadata: {
        previewUrl:
          "https://cdn.designcombo.dev/thumbnails/Happiness-shouldnt-depend.png",
      },
    },
    W1tb2sauODqNRhI5: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "If your happiness depends on the",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    N326snvPf9O1XWB: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "actions of others, you're at",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    cpamVHqGkxVnQ2qp: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "mercy of things that you can't",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    dvsBAKrDF6U0zTIV: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "control.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 75,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    YpZM0yJx04Zb03zH: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "Mhmm.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 75,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    CvXTedixwGMqnpS: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "And that's never where I want to be.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    M2Sv36YckryY0NAS: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "So I always want to live in, like, me",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    jxMeoaVX8BxOPEmS: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "and my therapist talk about like my",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    lM6VetPlAiCMU5T: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "higher goddess, my higher self.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    mdwLiXiu7SSFxSSB: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "Like I always want to live there",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    JC9MDYMvoHZkiu2w: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "knowing that when I'm there,",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    BWMEdVr9uGdg2pmN: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "you can't take that away from",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    uSEooSKedBQi9eV: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "me.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 75,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    a5JowII5uEpk6OQP: {
      type: "caption",
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "That that's mine.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 75,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    ic71GQgUoF393h2: {
      type: "audio",
      details: {
        src: "https://cdn.designcombo.dev/audio/Dawn%20of%20change.mp3",
        volume: 100,
      },
    },
    rmf4bMElei2wRe8G: {
      type: "text",
      details: {
        fontFamily: "Roboto-Bold",
        fontSize: 120,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ffffff",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "Heading and some body",
        opacity: 100,
        width: 600,
        wordWrap: "break-word",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: "750px",
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 420,
        fontUrl:
          "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#ffffff",
          x: 0,
          y: 0,
          blur: 0,
        },
      },
    },
  },
  trackItemIds: [
    "ic71GQgUoF393h2",
    "RZUICjMxa7r3tM8K",
    "a5JowII5uEpk6OQP",
    "uSEooSKedBQi9eV",
    "BWMEdVr9uGdg2pmN",
    "JC9MDYMvoHZkiu2w",
    "mdwLiXiu7SSFxSSB",
    "lM6VetPlAiCMU5T",
    "jxMeoaVX8BxOPEmS",
    "M2Sv36YckryY0NAS",
    "CvXTedixwGMqnpS",
    "YpZM0yJx04Zb03zH",
    "dvsBAKrDF6U0zTIV",
    "cpamVHqGkxVnQ2qp",
    "N326snvPf9O1XWB",
    "W1tb2sauODqNRhI5",
    "rmf4bMElei2wRe8G",
  ],
  transitionsMap: {},
  trackItemsMap: {
    RZUICjMxa7r3tM8K: {
      id: "RZUICjMxa7r3tM8K",
      metadata: {
        previewUrl:
          "https://cdn.designcombo.dev/thumbnails/Happiness-shouldnt-depend.png",
      },
      trim: {
        from: 0,
        to: 23870.113,
      },
      type: "video",
      name: "video",
      playbackRate: 1,
      display: {
        from: 0,
        to: 23870.113,
      },
      duration: 23870.113,
      isMain: false,
      details: {
        width: 360,
        height: 640,
        opacity: 100,
        src: "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        volume: 100,
        borderRadius: 0,
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        top: "640px",
        left: "360px",
        transform: "scale(3)",
        blur: 0,
        brightness: 100,
        flipX: false,
        flipY: false,
        rotate: "0deg",
        visibility: "visible",
      },
    },
    W1tb2sauODqNRhI5: {
      id: "W1tb2sauODqNRhI5",
      name: "caption",
      type: "caption",
      display: {
        from: 80,
        to: 3040,
      },
      metadata: {
        words: [
          {
            word: "If",
            start: 80,
            end: 240,
            confidence: 0.99063194,
          },
          {
            word: "your",
            start: 240,
            end: 480,
            confidence: 0.98874426,
          },
          {
            word: "happiness",
            start: 480,
            end: 980,
            confidence: 0.99995255,
          },
          {
            word: "depends",
            start: 1920,
            end: 2420,
            confidence: 0.99804354,
          },
          {
            word: "on",
            start: 2639.9999,
            end: 2879.9999000000003,
            confidence: 0.999602,
          },
          {
            word: "the",
            start: 2879.9999000000003,
            end: 3040,
            confidence: 0.99993205,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "If your happiness depends on the",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    N326snvPf9O1XWB: {
      id: "N326snvPf9O1XWB",
      name: "caption",
      type: "caption",
      display: {
        from: 3040.000000000001,
        to: 5279.999700000002,
      },
      metadata: {
        words: [
          {
            word: "actions",
            start: 3040,
            end: 3520,
            confidence: 0.9998667,
          },
          {
            word: "of",
            start: 3520,
            end: 3679.9998,
            confidence: 0.99996686,
          },
          {
            word: "others,",
            start: 3679.9998,
            end: 4180,
            confidence: 0.97919,
          },
          {
            word: "you're",
            start: 4720,
            end: 5040,
            confidence: 0.9944241,
          },
          {
            word: "at",
            start: 5040,
            end: 5279.9997,
            confidence: 0.9999274,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "actions of others, you're at",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    cpamVHqGkxVnQ2qp: {
      id: "cpamVHqGkxVnQ2qp",
      name: "caption",
      type: "caption",
      display: {
        from: 5279.9997,
        to: 6960,
      },
      metadata: {
        words: [
          {
            word: "mercy",
            start: 5279.9997,
            end: 5759.9998000000005,
            confidence: 0.99379504,
          },
          {
            word: "of",
            start: 5759.9998000000005,
            end: 6000,
            confidence: 0.9994796,
          },
          {
            word: "things",
            start: 6000,
            end: 6319.9997,
            confidence: 0.9998056,
          },
          {
            word: "that",
            start: 6319.9997,
            end: 6480,
            confidence: 0.9997929,
          },
          {
            word: "you",
            start: 6480,
            end: 6640,
            confidence: 0.9999223,
          },
          {
            word: "can't",
            start: 6640,
            end: 6960,
            confidence: 0.9999411,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "mercy of things that you can't",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    dvsBAKrDF6U0zTIV: {
      id: "dvsBAKrDF6U0zTIV",
      name: "caption",
      type: "caption",
      display: {
        from: 6959.999999999999,
        to: 7459.999999999999,
      },
      metadata: {
        words: [
          {
            word: "control.",
            start: 6960,
            end: 7460,
            confidence: 0.8020988,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "control.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 75,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    YpZM0yJx04Zb03zH: {
      id: "YpZM0yJx04Zb03zH",
      name: "caption",
      type: "caption",
      display: {
        from: 7759.9998000000005,
        to: 8080,
      },
      metadata: {
        words: [
          {
            word: "Mhmm.",
            start: 7759.9998000000005,
            end: 8080,
            confidence: 0.994252,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "Mhmm.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 75,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    CvXTedixwGMqnpS: {
      id: "CvXTedixwGMqnpS",
      name: "caption",
      type: "caption",
      display: {
        from: 8080,
        to: 10320,
      },
      metadata: {
        words: [
          {
            word: "And",
            start: 8080,
            end: 8240,
            confidence: 0.9979925,
          },
          {
            word: "that's",
            start: 8240,
            end: 8639.999,
            confidence: 0.9999033,
          },
          {
            word: "never",
            start: 8639.999,
            end: 9139.999,
            confidence: 0.9997875,
          },
          {
            word: "where",
            start: 9440,
            end: 9679.999,
            confidence: 0.9991536,
          },
          {
            word: "I",
            start: 9679.999,
            end: 9840,
            confidence: 0.9991804,
          },
          {
            word: "want",
            start: 9840,
            end: 10080,
            confidence: 0.5101704,
          },
          {
            word: "to",
            start: 10080,
            end: 10160,
            confidence: 0.9981395,
          },
          {
            word: "be.",
            start: 10160,
            end: 10320,
            confidence: 0.99637705,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "And that's never where I want to be.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    M2Sv36YckryY0NAS: {
      id: "M2Sv36YckryY0NAS",
      name: "caption",
      type: "caption",
      display: {
        from: 10320,
        to: 13155,
      },
      metadata: {
        words: [
          {
            word: "So",
            start: 10320,
            end: 10639.999,
            confidence: 0.9986513,
          },
          {
            word: "I",
            start: 10639.999,
            end: 10960,
            confidence: 0.99752027,
          },
          {
            word: "always",
            start: 10960,
            end: 11280,
            confidence: 0.66605484,
          },
          {
            word: "want",
            start: 11280,
            end: 11440,
            confidence: 0.7793616,
          },
          {
            word: "to",
            start: 11440,
            end: 11599.999,
            confidence: 0.99829227,
          },
          {
            word: "live",
            start: 11599.999,
            end: 11920,
            confidence: 0.99949336,
          },
          {
            word: "in,",
            start: 11920,
            end: 12160,
            confidence: 0.7462719,
          },
          {
            word: "like,",
            start: 12160,
            end: 12660,
            confidence: 0.7557821,
          },
          {
            word: "me",
            start: 12995,
            end: 13155,
            confidence: 0.99526125,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "So I always want to live in, like, me",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    jxMeoaVX8BxOPEmS: {
      id: "jxMeoaVX8BxOPEmS",
      name: "caption",
      type: "caption",
      display: {
        from: 13155,
        to: 14594.999,
      },
      metadata: {
        words: [
          {
            word: "and",
            start: 13155,
            end: 13315,
            confidence: 0.9875963,
          },
          {
            word: "my",
            start: 13315,
            end: 13394.999500000002,
            confidence: 0.99964476,
          },
          {
            word: "therapist",
            start: 13394.999500000002,
            end: 13875,
            confidence: 0.99102366,
          },
          {
            word: "talk",
            start: 13875,
            end: 14035,
            confidence: 0.9709709,
          },
          {
            word: "about",
            start: 14035,
            end: 14195,
            confidence: 0.9997305,
          },
          {
            word: "like",
            start: 14195,
            end: 14434.999,
            confidence: 0.97029567,
          },
          {
            word: "my",
            start: 14434.999,
            end: 14594.999,
            confidence: 0.98949206,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "and my therapist talk about like my",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    lM6VetPlAiCMU5T: {
      id: "lM6VetPlAiCMU5T",
      name: "caption",
      type: "caption",
      display: {
        from: 14594.999,
        to: 16515,
      },
      metadata: {
        words: [
          {
            word: "higher",
            start: 14594.999,
            end: 14915,
            confidence: 0.9981571,
          },
          {
            word: "goddess,",
            start: 14915,
            end: 15415,
            confidence: 0.98501575,
          },
          {
            word: "my",
            start: 15555,
            end: 15795,
            confidence: 0.9997985,
          },
          {
            word: "higher",
            start: 15795,
            end: 16114.999999999998,
            confidence: 0.9989059,
          },
          {
            word: "self.",
            start: 16114.999999999998,
            end: 16515,
            confidence: 0.921466,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "higher goddess, my higher self.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    mdwLiXiu7SSFxSSB: {
      id: "mdwLiXiu7SSFxSSB",
      name: "caption",
      type: "caption",
      display: {
        from: 16515,
        to: 18375,
      },
      metadata: {
        words: [
          {
            word: "Like",
            start: 16515,
            end: 16835,
            confidence: 0.9995938,
          },
          {
            word: "I",
            start: 16835,
            end: 16994.999,
            confidence: 0.76499707,
          },
          {
            word: "always",
            start: 16994.999,
            end: 17314.999,
            confidence: 0.9997514,
          },
          {
            word: "want",
            start: 17314.999,
            end: 17555,
            confidence: 0.9772455,
          },
          {
            word: "to",
            start: 17555,
            end: 17715,
            confidence: 0.9998716,
          },
          {
            word: "live",
            start: 17715,
            end: 17875,
            confidence: 0.99975175,
          },
          {
            word: "there",
            start: 17875,
            end: 18375,
            confidence: 0.9976922,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "Like I always want to live there",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    JC9MDYMvoHZkiu2w: {
      id: "JC9MDYMvoHZkiu2w",
      name: "caption",
      type: "caption",
      display: {
        from: 18835,
        to: 20914.999000000003,
      },
      metadata: {
        words: [
          {
            word: "knowing",
            start: 18835,
            end: 19335,
            confidence: 0.8706861,
          },
          {
            word: "that",
            start: 19955,
            end: 20115,
            confidence: 0.9986738,
          },
          {
            word: "when",
            start: 20115,
            end: 20435,
            confidence: 0.9907526,
          },
          {
            word: "I'm",
            start: 20435,
            end: 20595,
            confidence: 0.9998082,
          },
          {
            word: "there,",
            start: 20595,
            end: 20914.999000000003,
            confidence: 0.9904454,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "knowing that when I'm there,",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    BWMEdVr9uGdg2pmN: {
      id: "BWMEdVr9uGdg2pmN",
      name: "caption",
      type: "caption",
      display: {
        from: 20914.99900000001,
        to: 22435.000000000007,
      },
      metadata: {
        words: [
          {
            word: "you",
            start: 20914.999000000003,
            end: 21154.999,
            confidence: 0.99976164,
          },
          {
            word: "can't",
            start: 21154.999,
            end: 21395,
            confidence: 0.99960864,
          },
          {
            word: "take",
            start: 21395,
            end: 21634.998,
            confidence: 0.9991748,
          },
          {
            word: "that",
            start: 21634.998,
            end: 21875,
            confidence: 0.9996581,
          },
          {
            word: "away",
            start: 21875,
            end: 22195,
            confidence: 0.99991107,
          },
          {
            word: "from",
            start: 22195,
            end: 22435,
            confidence: 0.99937916,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "you can't take that away from",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 150,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    uSEooSKedBQi9eV: {
      id: "uSEooSKedBQi9eV",
      name: "caption",
      type: "caption",
      display: {
        from: 22435,
        to: 22835,
      },
      metadata: {
        words: [
          {
            word: "me.",
            start: 22435,
            end: 22835,
            confidence: 0.9003741,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "me.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 75,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    a5JowII5uEpk6OQP: {
      id: "a5JowII5uEpk6OQP",
      name: "caption",
      type: "caption",
      display: {
        from: 22835,
        to: 23870.062,
      },
      metadata: {
        words: [
          {
            word: "That",
            start: 22835,
            end: 23075,
            confidence: 0.9848171,
          },
          {
            word: "that's",
            start: 23075,
            end: 23395,
            confidence: 0.88075125,
          },
          {
            word: "mine.",
            start: 23395,
            end: 23870.062,
            confidence: 0.98580784,
          },
        ],
        sourceUrl:
          "https://cdn.designcombo.dev/videos/Happiness%20shouldn%E2%80%99t%20depend.mp4",
        parentId: "RZUICjMxa7r3tM8K",
      },
      isMain: false,
      details: {
        fontFamily: "theboldfont",
        fontSize: 60,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ff4757",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "That that's mine.",
        opacity: 100,
        width: 600,
        wordWrap: "normal",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: 800,
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 75,
        fontUrl: "https://cdn.designcombo.dev/fonts/the-bold-font.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#000000",
          x: 0,
          y: 0,
          blur: 0,
        },
        words: [],
      },
    },
    ic71GQgUoF393h2: {
      id: "ic71GQgUoF393h2",
      name: "Dawn of change",
      type: "audio",
      display: {
        from: 0,
        to: 117242.83300000001,
      },
      trim: {
        from: 0,
        to: 117242.833,
      },
      playbackRate: 1,
      metadata: {
        author: "Roman Senyk",
      },
      duration: 117242.833,
      details: {
        src: "https://cdn.designcombo.dev/audio/Dawn%20of%20change.mp3",
        volume: 100,
      },
    },
    rmf4bMElei2wRe8G: {
      id: "rmf4bMElei2wRe8G",
      name: "text",
      type: "text",
      display: {
        from: 24920.212765957447,
        to: 29920.212765957447,
      },
      metadata: {},
      isMain: false,
      details: {
        fontFamily: "Roboto-Bold",
        fontSize: 120,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        textAlign: "center",
        lineHeight: "normal",
        letterSpacing: "normal",
        wordSpacing: "normal",
        color: "#ffffff",
        backgroundColor: "transparent",
        border: "none",
        textShadow: "none",
        text: "Heading and some body",
        opacity: 100,
        width: 600,
        wordWrap: "break-word",
        wordBreak: "normal",
        WebkitTextStrokeColor: "#ffffff",
        WebkitTextStrokeWidth: "0px",
        top: "750px",
        left: "240px",
        textTransform: "none",
        transform: "none",
        skewX: 0,
        skewY: 0,
        height: 420,
        fontUrl:
          "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
        borderWidth: 0,
        borderColor: "#000000",
        boxShadow: {
          color: "#ffffff",
          x: 0,
          y: 0,
          blur: 0,
        },
      },
      animations: {
        in: {
          name: "scaleIn",
          composition: [
            {
              property: "scale",
              from: 0,
              to: 1,
              durationInFrames: 15,
            },
          ],
        },
        out: {
          name: "fadeOut",
          composition: [
            {
              property: "opacity",
              from: 1,
              to: 0,
              durationInFrames: 15,
            },
          ],
        },
      },
    },
  },
  transitionIds: [],
};
